<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\CountryJp;
use Carbon\Carbon; // 日付関連操作に


class AddCountryController extends Controller
{
    //
    DB::table('countryJp')->insertGetId([
        ['name' => 'アイスランド', 'code' => 'IS', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'アイルランド', 'code' => 'IE', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'アゼルバイジャン', 'code' => 'AZ', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'アフガニスタン', 'code' => 'AF', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'アメリカ合衆国', 'code' => 'US', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'アラブ首長国連邦', 'code' => 'AE', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'アルジェリア', 'code' => 'DZ','created_at' => now(),'updated_at' => now()],
        ['name' => 'アルゼンチン', 'code' => 'AR','created_at' => now(),'updated_at' => now()],
        ['name' => 'アルバニア', 'code' => 'AL', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'アルメニア', 'code' => 'AM', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'アンゴラ', 'code' => 'AO', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'アンティグア・バーブーダ', 'code' => 'AG', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'アンドラ', 'code' => 'AD', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'イエメン', 'code' => 'YE', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'イギリス ', 'code' => 'GB', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'イスラエル', 'code' => 'IL', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'イタリア', 'code' => 'IT', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'インド', 'code' => 'IN', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'インドネシア', 'code' => 'ID', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'ウガンダ', 'code' => 'UG', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'ウクライナ', 'code' => 'UA', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'ウズベキスタン', 'code' => 'UZ', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'ウルグアイ', 'code' => 'UY', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'エクアドル', 'code' => 'EC', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'エジプト', 'code' => 'EG', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'エストニア', 'code' => 'EE', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'エスワティニ（スワジランド）', 'code' => 'SZ', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'エチオピア', 'code' => 'ET', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'エリトリア', 'code' => 'ER', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'エルサルバドル', 'code' => 'SV', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'オーストラリア', 'code' => 'AU', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'オーストリア', 'code' => 'AT', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'オマーン', 'code' => 'OM', 'created_at' => now(),'updated_at' => now()],
        ['name' => 'オランダ', 'code' => 'NL', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
        ['name' => '', 'code' => '', 'created_at' => now(),'updated_at' => now()],
    ]);

}
